//
//  CountriesAppApp.swift
//  CountriesApp
//
//  Created by MANAS VIJAYWARGIYA on 27/12/24.
//
// Get Started with Apollo Docs - https://www.apollographql.com/docs/ios/get-started
// GraphQL queries use this website or the app installed in the Mac - https://graphql-demo.mead.io


// First Install node npm.
// Second Install  npm install -g apollo
// Third install apollo-ios SPM package in the App. Follow from this link - https://www.apollographql.com/docs/ios/get-started

/* Download Schema by using the GraphQL App installed in Mac or by using Apollo CLI - Apollo CLI steps to download GraphQL Schema */
/*
 In Terminal, Go to Root of the project. -> type - apollo schema:download --endpoint=https://countries.trevorblades.com/
 Then add that Schema.json file into the project.
 Then create a file Queries.graphql
 Also create a new file in the same GraphQL folder named as Apollo. Add Apollo Client URL for GraphQL queries - https://countries.trevorblades.com/ */

/* To create API file that will be automatically be generated by using this steps - */
/*
 cd Desktop -> cd GraphQl_SwiftUI -> cd CountriesApp -> cd CountriesApp again and run this command in terminal to generate API.swift file
 apollo codegen:generate --target=swift --includes=./GraphQL/Queries.graphql --localSchemaFile="./GraphQL/schema.json" ./GraphQL/API.swift
 
*/

import SwiftUI

@main
struct CountriesAppApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
